### ISSUE TITLE
op movement

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#136]
- [x] 'grab' a panel by hovering and pressing + holding the controller select button
- [x] op can move with controller
- [ ] any plugged cables move with connected op --  (see issue #117)
- [x] panel position moves accurately with end of raycast
- [x] panel z can be moved by controller thumbstick 'y'
- [ ] panel z moves along controller z
- [x] panel rotation on Y axis can be changed by controller thumbstick 'x'
- [ ] panel rotation on Y axis is behaves consistently
- [x] op can be deleted from scene if moved below the scene floor -- see progress with issue #137 
- [ ] when op is deleted, all of its connected cables are immediately deleted as well
- [x] replace inlets/outlets geometry with a torusgeometry shape

## problems
- [ ] selecting and moving an op, afterwards its not easy to grab another op. the previous stays attached to the controller
- [x] sometimes the op is deleted after moving it - resolved by issue #143

**Comment by michaelpalumbo** [comment]
4.x abandoned. archived in [mischmaschWeb](https://github.com/worldmaking/mischmaschWeb)
