### ISSUE TITLE
sound not working on meta quest 3

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#268]
- [x] plays audio from meta quest apps
- [x] plays audio from steamvr
- [ ] plays audio from oculus app
- [ ] plays audio from mischmasch
